freebox with home / dathosim
hacf-fr/home-assistant-core pull request #90
Opened 2021-10-12 15:37 UTC by dathosim

- init de la constante VALUE_NOT_SET manquante dans const.py (sinon erreur à l'init) 
- supression de la dependance a generic : sinon on passe pas le config flow
- suppression des start_watcher dans les binary sensor : sinon erreur à l'init - attribut n'existe pas

Après vérification, cela rend l'intégration installable mais l'update des sensor ne se fait pas.
En effet, il n'ya plus d'appel à un watcher ou updater lors du changement d'état (car j'ai  commenté les lignes self.start_watcher qui était en erreur)
J'ai beau remonté dans l'historique du code je n'arrive pas à comprendre comment cela devrait être codé pour que ça marche.

Mais au moins avec cette PR l'intégration peut être installé entièrement et détecte tous les device du pack sécurité

2021-10-17 06:51 UTC, oncleben31 requested changes
J'ai l'impression que cette branch a pris beaucoup d'écart par rapport à la branche de dev officielle.
Il y a eu des modifications sur l'integration Freebox depuis. Le merge risque d'être compliqué.

Je vois deux options:
 - refaire une branch home à partir d'une branche dev plus récente.
 - développer la partie Home dans un custom composent pour permettre à la communauté de beta testé et merge dans l'integration officielle en un second temps.

@Quentame @gvigroux un avis ?

2021-10-17 06:51 UTC, oncleben31 commented on homeassistant/components/freebox/alarm_control_panel.py
> +            """self.start_watcher(timedelta(seconds=1))"""
La notation `"""` est réservée pour les [docstrings](https://www.python.org/dev/peps/pep-0257/).
Tu dois utiliser `#` pour commenter du code.

2021-10-17 06:51 UTC, oncleben31 commented on homeassistant/components/freebox/base_class.py
> +    def stop_watcher(self):
J'ai l'impression que tu as crée ici une fonction qui n'est pas utliisé.

2021-10-17 16:47 UTC, dathosim commented on homeassistant/components/freebox/alarm_control_panel.py
> +            """self.start_watcher(timedelta(seconds=1))"""
Merci pour la remarque mais en fait, dans le commit suivant jai supprimé le commentaire et remis l'appel à cette méthode

2021-10-18 20:48 UTC, oncleben31 commented on homeassistant/components/freebox/alarm_control_panel.py
> +            """self.start_watcher(timedelta(seconds=1))"""
Que veux tu dire par commit suivant ? La revue ce fait sur l'état après le dernier commit sur cette PR. Est-ce que tu ne confond pas commit et PR ?

2021-10-20 13:07 UTC, dathosim commented on homeassistant/components/freebox/alarm_control_panel.py
> +            """self.start_watcher(timedelta(seconds=1))"""
en fait, je ne confond pas commit et PR mais je croyais que mon nouveau commit qui a eu lieu un jour après était intégré à cette PR - en fait il est dans une nouvelle PR 
https://github.com/hacf-fr/home-assistant-core/pull/91
J'aurai bien aimé ajouter ce commit à la PR mais ça semble compliqué et je croyais avoir réussi

Dans cette nouvelle PR j'ai supprimé les commentaires devant les appels à start_watcher car j'ai ajouté la méthode pour que les sensor se mettent à jour - sinon dans la PR 90, l'intégration s'installait mais les sensor ne se mettaient pas à jour dans HA

2021-10-20 13:08 UTC, dathosim commented on homeassistant/components/freebox/base_class.py
> +    def stop_watcher(self):
la fonction stop_watcher semble être appelé dans la alarm_control_panel.py 
Elle serait donc utile...

2021-11-26 13:23 UTC, closed without merging